[project]
name = "nosh-recipe-gen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agno==2.0.11",
    "arize-phoenix>=12.6.1",
    "boto3>=1.40.57",
    "evaluate>=0.4.6",
    "flask==3.1.1",
    "google-api-python-client==2.176.0",
    "google-genai==1.46.0",
    "google-generativeai>=0.8.5",
    "gunicorn==23.0.0",
    "isodate==0.7.2",
    "jsonschema==4.23.0",
    "nltk>=3.9.1",
    "numpy>=2.3.2",
    "openai>=2.1.0",
    "openinference-instrumentation-agno>=0.1.18",
    "openinference-instrumentation-google-genai>=0.1.8",
    "openpyxl==3.1.5",
    "opentelemetry-exporter-otlp>=1.37.0",
    "opentelemetry-instrumentation-flask>=0.45b0",
    "opentelemetry-instrumentation-requests>=0.45b0",
    "opentelemetry-sdk>=1.37.0",
    "pandas>=2.3.2",
    "pydantic-xml>=2.17.3",
    "qdrant-client>=1.18.0",
    "langgraph>=1.2.6",
    "rouge-score>=0.1.2",
]
